### ISSUE TITLE
Design API to support fetching of "lookup data"

### ISSUE THREAD

**Issue by rclanan** [fusionalliance/autorenter-nodeexpress-api#17]
Verbs Supported: GET
Design route to support lookup data (states, colors, makes, models, years).

This data is read-only. Any maintenance will be via code updates.

I'm thinking a single path with composable query string options...

**Comment by BWortman** [comment]
Implemented and tested, but I still need to update the api doc.

**Comment by BWortman** [comment]
Just updated the api design doc. Closing.
