### ISSUE TITLE
Replace callbacks with promises in tests

### ISSUE THREAD

**Issue by rclanan** [fusionalliance/autorenter-nodeexpress-api#28]
Due to some well-known bugs with the test frameworks (supertest-as-promised and chai-http, for example), we were forced to use a callback-based approach in our tests (e.g., getRoot.js). The tests were always passing when using a promise-based approach, swallowing all errors. 

We figured it's better to have tests that use callbacks and work than tests that use promises and don't work... but eventually we want tests that use promises and also actually work ;-)

**Comment by BWortman** [comment]
Good idea, but we're not going to get to this any time soon. Closing it.
