### ISSUE TITLE
Include a .env-example in the repo, remove .env from repo and git ignore it.

### ISSUE THREAD

**Issue by camoore1979** [fusionalliance/autorenter-nodeexpress-api#65]
The .env file needs to be flexible for local use, and should not be checked into repo.

- [ ] include a .env.example in the repo.
- [ ] remove .env from repo
- [ ] git ignore .env

**Comment by BWortman** [comment]
This broke the travis build, but I'll open a separate issue for that...

**Comment by BWortman** [comment]
Good news. I added environment vars to travis ci, and that fixed the build.
